// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/khu-dev/khumu-comment/usecase (interfaces: CommentUseCaseInterface,LikeCommentUseCaseInterface)

// Package usecase is a generated GoMock package.
package usecase

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	data "github.com/khu-dev/khumu-comment/data"
	repository "github.com/khu-dev/khumu-comment/repository"
)

// MockCommentUseCaseInterface is a mock of CommentUseCaseInterface interface.
type MockCommentUseCaseInterface struct {
	ctrl     *gomock.Controller
	recorder *MockCommentUseCaseInterfaceMockRecorder
}

// MockCommentUseCaseInterfaceMockRecorder is the mock recorder for MockCommentUseCaseInterface.
type MockCommentUseCaseInterfaceMockRecorder struct {
	mock *MockCommentUseCaseInterface
}

// NewMockCommentUseCaseInterface creates a new mock instance.
func NewMockCommentUseCaseInterface(ctrl *gomock.Controller) *MockCommentUseCaseInterface {
	mock := &MockCommentUseCaseInterface{ctrl: ctrl}
	mock.recorder = &MockCommentUseCaseInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommentUseCaseInterface) EXPECT() *MockCommentUseCaseInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCommentUseCaseInterface) Create(arg0 *data.CommentInput) (*data.CommentOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(*data.CommentOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockCommentUseCaseInterfaceMockRecorder) Create(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCommentUseCaseInterface)(nil).Create), arg0)
}

// Delete mocks base method.
func (m *MockCommentUseCaseInterface) Delete(arg0 string, arg1 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCommentUseCaseInterfaceMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCommentUseCaseInterface)(nil).Delete), arg0, arg1)
}

// Get mocks base method.
func (m *MockCommentUseCaseInterface) Get(arg0 string, arg1 int) (*data.CommentOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(*data.CommentOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockCommentUseCaseInterfaceMockRecorder) Get(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCommentUseCaseInterface)(nil).Get), arg0, arg1)
}

// List mocks base method.
func (m *MockCommentUseCaseInterface) List(arg0 string, arg1 *repository.CommentQueryOption) ([]*data.CommentOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1)
	ret0, _ := ret[0].([]*data.CommentOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockCommentUseCaseInterfaceMockRecorder) List(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockCommentUseCaseInterface)(nil).List), arg0, arg1)
}

// Update mocks base method.
func (m *MockCommentUseCaseInterface) Update(arg0 string, arg1 int, arg2 map[string]interface{}) (*data.CommentOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1, arg2)
	ret0, _ := ret[0].(*data.CommentOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockCommentUseCaseInterfaceMockRecorder) Update(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCommentUseCaseInterface)(nil).Update), arg0, arg1, arg2)
}

// MockLikeCommentUseCaseInterface is a mock of LikeCommentUseCaseInterface interface.
type MockLikeCommentUseCaseInterface struct {
	ctrl     *gomock.Controller
	recorder *MockLikeCommentUseCaseInterfaceMockRecorder
}

// MockLikeCommentUseCaseInterfaceMockRecorder is the mock recorder for MockLikeCommentUseCaseInterface.
type MockLikeCommentUseCaseInterfaceMockRecorder struct {
	mock *MockLikeCommentUseCaseInterface
}

// NewMockLikeCommentUseCaseInterface creates a new mock instance.
func NewMockLikeCommentUseCaseInterface(ctrl *gomock.Controller) *MockLikeCommentUseCaseInterface {
	mock := &MockLikeCommentUseCaseInterface{ctrl: ctrl}
	mock.recorder = &MockLikeCommentUseCaseInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLikeCommentUseCaseInterface) EXPECT() *MockLikeCommentUseCaseInterfaceMockRecorder {
	return m.recorder
}

// Toggle mocks base method.
func (m *MockLikeCommentUseCaseInterface) Toggle(arg0 *data.LikeCommentInput) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Toggle", arg0)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Toggle indicates an expected call of Toggle.
func (mr *MockLikeCommentUseCaseInterfaceMockRecorder) Toggle(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Toggle", reflect.TypeOf((*MockLikeCommentUseCaseInterface)(nil).Toggle), arg0)
}
