// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/khu-dev/khumu-comment/repository (interfaces: EventMessageRepository,CommentRepositoryInterface,LikeCommentRepositoryInterface)

// Package repository is a generated GoMock package.
package repository

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/khu-dev/khumu-comment/model"
)

// MockEventMessageRepository is a mock of EventMessageRepository interface.
type MockEventMessageRepository struct {
	ctrl     *gomock.Controller
	recorder *MockEventMessageRepositoryMockRecorder
}

// MockEventMessageRepositoryMockRecorder is the mock recorder for MockEventMessageRepository.
type MockEventMessageRepositoryMockRecorder struct {
	mock *MockEventMessageRepository
}

// NewMockEventMessageRepository creates a new mock instance.
func NewMockEventMessageRepository(ctrl *gomock.Controller) *MockEventMessageRepository {
	mock := &MockEventMessageRepository{ctrl: ctrl}
	mock.recorder = &MockEventMessageRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventMessageRepository) EXPECT() *MockEventMessageRepositoryMockRecorder {
	return m.recorder
}

// PublishCommentEvent mocks base method.
func (m *MockEventMessageRepository) PublishCommentEvent(arg0 *model.EventMessage) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PublishCommentEvent", arg0)
}

// PublishCommentEvent indicates an expected call of PublishCommentEvent.
func (mr *MockEventMessageRepositoryMockRecorder) PublishCommentEvent(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishCommentEvent", reflect.TypeOf((*MockEventMessageRepository)(nil).PublishCommentEvent), arg0)
}

// publishCommentEvent mocks base method.
func (m *MockEventMessageRepository) publishCommentEvent(arg0 *model.EventMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "publishCommentEvent", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// publishCommentEvent indicates an expected call of publishCommentEvent.
func (mr *MockEventMessageRepositoryMockRecorder) publishCommentEvent(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "publishCommentEvent", reflect.TypeOf((*MockEventMessageRepository)(nil).publishCommentEvent), arg0)
}

// MockCommentRepositoryInterface is a mock of CommentRepositoryInterface interface.
type MockCommentRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockCommentRepositoryInterfaceMockRecorder
}

// MockCommentRepositoryInterfaceMockRecorder is the mock recorder for MockCommentRepositoryInterface.
type MockCommentRepositoryInterfaceMockRecorder struct {
	mock *MockCommentRepositoryInterface
}

// NewMockCommentRepositoryInterface creates a new mock instance.
func NewMockCommentRepositoryInterface(ctrl *gomock.Controller) *MockCommentRepositoryInterface {
	mock := &MockCommentRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockCommentRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommentRepositoryInterface) EXPECT() *MockCommentRepositoryInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCommentRepositoryInterface) Create(arg0 *model.Comment) (*model.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(*model.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockCommentRepositoryInterfaceMockRecorder) Create(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCommentRepositoryInterface)(nil).Create), arg0)
}

// Delete mocks base method.
func (m *MockCommentRepositoryInterface) Delete(arg0 int) (*model.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0)
	ret0, _ := ret[0].(*model.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockCommentRepositoryInterfaceMockRecorder) Delete(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCommentRepositoryInterface)(nil).Delete), arg0)
}

// Get mocks base method.
func (m *MockCommentRepositoryInterface) Get(arg0 int) (*model.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0)
	ret0, _ := ret[0].(*model.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockCommentRepositoryInterfaceMockRecorder) Get(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCommentRepositoryInterface)(nil).Get), arg0)
}

// List mocks base method.
func (m *MockCommentRepositoryInterface) List(arg0 *CommentQueryOption) []*model.Comment {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0)
	ret0, _ := ret[0].([]*model.Comment)
	return ret0
}

// List indicates an expected call of List.
func (mr *MockCommentRepositoryInterfaceMockRecorder) List(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockCommentRepositoryInterface)(nil).List), arg0)
}

// Update mocks base method.
func (m *MockCommentRepositoryInterface) Update(arg0 int, arg1 map[string]interface{}) (*model.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(*model.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockCommentRepositoryInterfaceMockRecorder) Update(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCommentRepositoryInterface)(nil).Update), arg0, arg1)
}

// MockLikeCommentRepositoryInterface is a mock of LikeCommentRepositoryInterface interface.
type MockLikeCommentRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockLikeCommentRepositoryInterfaceMockRecorder
}

// MockLikeCommentRepositoryInterfaceMockRecorder is the mock recorder for MockLikeCommentRepositoryInterface.
type MockLikeCommentRepositoryInterfaceMockRecorder struct {
	mock *MockLikeCommentRepositoryInterface
}

// NewMockLikeCommentRepositoryInterface creates a new mock instance.
func NewMockLikeCommentRepositoryInterface(ctrl *gomock.Controller) *MockLikeCommentRepositoryInterface {
	mock := &MockLikeCommentRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockLikeCommentRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLikeCommentRepositoryInterface) EXPECT() *MockLikeCommentRepositoryInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockLikeCommentRepositoryInterface) Create(arg0 *model.LikeComment) (*model.LikeComment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(*model.LikeComment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockLikeCommentRepositoryInterfaceMockRecorder) Create(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockLikeCommentRepositoryInterface)(nil).Create), arg0)
}

// Delete mocks base method.
func (m *MockLikeCommentRepositoryInterface) Delete(arg0 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockLikeCommentRepositoryInterfaceMockRecorder) Delete(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockLikeCommentRepositoryInterface)(nil).Delete), arg0)
}

// List mocks base method.
func (m *MockLikeCommentRepositoryInterface) List(arg0 *LikeCommentQueryOption) []*model.LikeComment {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0)
	ret0, _ := ret[0].([]*model.LikeComment)
	return ret0
}

// List indicates an expected call of List.
func (mr *MockLikeCommentRepositoryInterfaceMockRecorder) List(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockLikeCommentRepositoryInterface)(nil).List), arg0)
}
