host: "0.0.0.0"
restRootEndpoint: "http://localhost:9000/api/"
port: "9000"
db:
  type: sqlite3
  sqlite3:
#    filePath: "/home/jinsu/git/khumu/khumu-command-center/db.sqlite3"
    filePath: "/home/jinsu/git/khumu/khumu-comment/test.sqlite3"
