host: "0.0.0.0"
restRootEndpoint: "http://localhost:9000/api/"
port: 9000
db:
  kind: sqlite3
  sqlite3:
    filePath: "test.sqlite3"
  mysql:
    host: 192.168.0.1 # Define YOUR_MYSQL_HOSTNAME
    port: 3306 # Define YOUR_MYSQL_PORT
    databaseName: test # Define YOUR_MYSQL_DATABASE_NAME
    user: root # Define YOUR_MYSQL_USER
    password: root # Define YOUR_MYSQL_PASSWORD
redis:
  address: "example.com:6379"
  password: ""
  db: 0
  commentChannel: your_comment_channel
  likeCommentChannel: your_like_comment
sns:
  topicArn: arn:aws:sns:ap-northeast-2:xxx
