// Code generated by entc, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/khu-dev/khumu-comment/ent/article"
	"github.com/khu-dev/khumu-comment/ent/comment"
	"github.com/khu-dev/khumu-comment/ent/khumuuser"
	"github.com/khu-dev/khumu-comment/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	articleFields := schema.Article{}.Fields()
	_ = articleFields
	// articleDescCreatedAt is the schema descriptor for created_at field.
	articleDescCreatedAt := articleFields[1].Descriptor()
	// article.DefaultCreatedAt holds the default value on creation for the created_at field.
	article.DefaultCreatedAt = articleDescCreatedAt.Default.(func() time.Time)
	commentFields := schema.Comment{}.Fields()
	_ = commentFields
	// commentDescState is the schema descriptor for state field.
	commentDescState := commentFields[1].Descriptor()
	// comment.DefaultState holds the default value on creation for the state field.
	comment.DefaultState = commentDescState.Default.(string)
	// commentDescCreatedAt is the schema descriptor for created_at field.
	commentDescCreatedAt := commentFields[3].Descriptor()
	// comment.DefaultCreatedAt holds the default value on creation for the created_at field.
	comment.DefaultCreatedAt = commentDescCreatedAt.Default.(func() time.Time)
	khumuuserFields := schema.KhumuUser{}.Fields()
	_ = khumuuserFields
	// khumuuserDescStatus is the schema descriptor for status field.
	khumuuserDescStatus := khumuuserFields[2].Descriptor()
	// khumuuser.DefaultStatus holds the default value on creation for the status field.
	khumuuser.DefaultStatus = khumuuserDescStatus.Default.(string)
}
